name: Update About Metadata

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-about:
    runs-on: ubuntu-latest
    steps:
      - name: Update Repo Metadata
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo edit Roskud/epic-mickey-2-60fps-unlock \
            --description "🎮 60 FPS frame rate unlocker & physics fix for Disney Epic Mickey 2: The Power of Two on Windows and Steam Deck (SteamOS)." \
            --add-topic "epic-mickey" \
            --add-topic "epic-mickey-2" \
            --add-topic "60fps" \
            --add-topic "fps-unlock" \
            --add-topic "steam-deck" \
            --add-topic "steamos" \
            --add-topic "disney-epic-mickey-2" \
            --add-topic "pcgamingwiki" \
            --add-topic "gamebryo" \
            --add-topic "proton" \
            --enable-issues=true
